# --- ОПТИМИЗАЦИЯ ПРОИЗВОДИТЕЛЬНОСТИ ---
# sendfile on;
tcp_nopush on;
tcp_nodelay on;
# keepalive_timeout 65;
types_hash_max_size 2048;

# MIME-типы и кодировка по умолчанию
include /etc/nginx/mime.types;
# default_type application/octet-stream;

# Настройки логов
access_log /dev/stdout;
error_log /dev/stderr warn;

# Настройки сжатия gzip
gzip on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_disable "msie6";
gzip_vary  on;
gzip_min_length 512;
gzip_types text/plain
           text/css
           application/json
           application/x-javascript
           text/xml application/xml
           application/xml+rss
           text/javascript
           application/javascript
           application/vnd.ms-fontobject
           application/x-font-ttf
           font/opentype
           image/svg+xml
           image/x-icon;

# --- КОНФИГУРАЦИЯ СЕРВЕРА ---
server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
