"""
Django settings for lpon_site project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Читаем переменные окружения
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))

def _normalize_admin_url(value: str) -> str:
    """Приводит URL админки к виду `segment/` без ведущего слэша."""
    normalized = value.strip().lstrip('/')
    if not normalized:
        return 'admin/'
    if not normalized.endswith('/'):
        normalized += '/'
    return normalized

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='3xym$l+!)erah-k23lf0=t=c_4$e0nr*zls&l%pbz@k6v6qn89')
ADMIN_URL = _normalize_admin_url(env('DJANGO_ADMIN_URL', default='admin/'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = env.list(
    'DJANGO_ALLOWED_HOSTS',
    default=['127.0.0.1', 'localhost', 'testserver', 'lpon.ru'],
)

CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=['127.0.0.1', 'localhost', 'testserver'])

#########################################
# Настройки сообщений об ошибках когда все упало и т.п.
ADMINS = tuple(
    tuple(item.split(':', 1))
    for item in env.list('DJANGO_ADMINS', default=['S.Erjemin:erjemin@gmail.com'])
)

# Application definition

INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Django-filer и его зависимости
    # Порядок важен! polymorphic должен быть ДО filer, easy_thumbnails тоже ДО filer
    'polymorphic',
    'easy_thumbnails',
    'filer',
    # Наше приложение
    'frontend.apps.FrontendConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lpon_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lpon_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.parent.joinpath('database', env('DJANGO_SQLITE_NAME', default='lpon-db.sqlite3')),
        'CONN_MAX_AGE': 600,        #  время жизни соединения с базой
        'OPTIONS': {
            'timeout': 25,
            'init_command': "PRAGMA journal_mode=WAL; PRAGMA auto_vacuum=2;",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'ru-RU'         #
# TIME_ZONE = 'Etc/GMT+3'       #
TIME_ZONE = 'Europe/Moscow'     #
USE_I18N = True
USE_TZ = True
FIRST_DAY_OF_WEEK = 1           # неделя начинается с понедельника
DEFAULT_CHARSET = 'utf-8'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
# Локальные каталоги проекта: медиа и статика лежат рядом в `public`.
PUBLIC_DIR = BASE_DIR.parent.joinpath('public')     # Папка `public` находится в корне пректа
MEDIA_ROOT = PUBLIC_DIR.joinpath('media')
STATICFILES_DIRS = [PUBLIC_DIR.joinpath('static')]
STATIC_ROOT = PUBLIC_DIR.joinpath('staticfiles')


# ============================================================================
# Django-Filer Configuration (для загрузки файлов через админку)
# ============================================================================
# django-filer использует easy_thumbnails для управления вариантами изображений
# Все файлы хранятся в MEDIA_ROOT/filer_public/ и MEDIA_ROOT/filer_private/

FILER_ENABLE_PERMISSIONS = DEBUG  # В production установить True для ограничения доступа

# Разрешенные расширения файлов для FilerImageField
FILER_WHITELIST_FOR_PATH_ACCESS = (
    # ПОДУМАТЬ: поддержка '.heic' требует дополнительных пакетов (и разных для прода и дева) + обработчик сигналов
    #           для автоматической конвертации .heic в .webp при загрузке. Пока отключаем, и оставим на будущее
    '.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp', # Изображения
    '.doc', '.docx', '.pdf', '.txt', '.xls', '.xlsx', '.csv',  # Документы
)

# Максимальный размер загружаемого файла (в байтах): 100 MB
FILER_MAX_UPLOAD_SIZE = 100 * 1024 * 1024

# Tiny Image Specifications для автоматических вариантов изображений
THUMBNAIL_ALIASES = {
    '': {
        # Для галерей и витрин
        # Кратные 16х16 картинки для ускорения GPU-рендера браузеров, retina-дисплеев и "копеечная" экономии на сервере
        'admin_thumbnail': {'size': (64, 64), 'crop': True},  # Для админки
        'small': {'size': (256, 256), 'crop': True},        # Квадрат 256x256 для миниатюр
        'medium': {'size': (512, 512), 'crop': True},       # Квадрат 512x512 для просмотра
        'large': {'size': (1024, 1024), 'crop': 'smart'},   # Большое изображение с умным crop
    },
}

# Форматы сохранения для thumbnail'ов (миниатюр)
THUMBNAIL_PRESERVE_FORMAT = False   # Не сохранять оригинальный формат для thumbnails
THUMBNAIL_FORMAT = 'WEBP'           # Конвертировать все thumbnails в WebP
THUMBNAIL_WEBP_QUALITY = 80         # Качество WebP (достаточно 75-85 для thumbnails)

# Интерпретатор для обработки изображений
THUMBNAIL_ENGINE = 'easy_thumbnails.engines.pil_engine.PilEngine'

# Качество JPEG при сжатии (0-100, по умолчанию 85)
# THUMBNAIL_QUALITY = 85

# Источник кеша для миниатюр
THUMBNAIL_DEBUG = DEBUG  # Показывать ошибки генерирования миниатюр в debug режиме

