# Generated by Django 6.0.5 on 2026-07-10 13:40

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_tbarticle_k_article_to_image_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbimagemetadata',
            name='f_img_confidence_score',
        ),
        migrations.RemoveField(
            model_name='tbimagemetadata',
            name='l_img_reality',
        ),
        migrations.RemoveField(
            model_name='tbimagemetadata',
            name='l_img_source',
        ),
        migrations.RemoveField(
            model_name='tbimagemetadata',
            name='s_img_src_url',
        ),
        migrations.RemoveField(
            model_name='tbimagemetadata',
            name='t_img_created',
        ),
        migrations.RemoveField(
            model_name='tbimagemetadata',
            name='t_img_updated',
        ),
        migrations.RemoveField(
            model_name='tboffer',
            name='k_offer_to_image',
        ),
        migrations.AddField(
            model_name='tbimagemetadata',
            name='m_offer',
            field=models.ForeignKey(blank=True, help_text='Оффер, к которому привязана эта картинка (может быть пусто, если оффер удален)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m_image', to='frontend.tboffer', verbose_name='Оффер'),
        ),
        migrations.AddField(
            model_name='tboffer',
            name='m_offer_to_image',
            field=models.ManyToManyField(blank=True, help_text='Картинки этого предложения (обложка, задник, фото и т.д). Управляются в админке TbImageMetadata с сортировкой (i_img_sort) и метаданными (j_img_metadata). Доступ в коде: offer.m_image.all() (все TbImageMetadata, отсортированные) или offer.m_offer_to_image.all() (все картинки). Каждая запись TbImageMetadata содержит: image, m_offer, i_img_sort, j_img_metadata.', related_name='m_image_to_offer', through='frontend.TbImageMetadata', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображения товара'),
        ),
        migrations.AlterField(
            model_name='tbarticle',
            name='k_article_to_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Обложка или иллюстрация статьи из файлового хранилища (django_filer). Метаданные: image.metadata.i_img_sort и image.metadata.j_img_metadata.</br><b>ВАЖНО</b>: Так как статья призывается к исполнителям, лейблам, продавцам, музыкальным стилям, её можно использовать как логотип-пкитограмму или баннер этих сущностей. В этом случае  рекомендуется использовать изображение с прозрачным фоном (движок поддерживает SVG, WebP и PNG).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_to_article', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение для статьи'),
        ),
        migrations.AlterField(
            model_name='tbimagemetadata',
            name='image',
            field=filer.fields.image.FilerImageField(help_text='Файл изображения из django_filer.', on_delete=django.db.models.deletion.CASCADE, related_name='m_offer', to=settings.FILER_IMAGE_MODEL, verbose_name='Файл изображения'),
        ),
    ]
