# Generated by Django 6.0.5 on 2026-08-03 19:55

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_tbarticle_k_article_to_image_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tboffer',
            name='s_offer_skip32',
        ),
        migrations.AddField(
            model_name='tbarticle',
            name='i_article_sort',
            field=models.IntegerField(db_index=True, default=0, help_text='Сортировка/Приоритет для HUB. Статьи-хабы (и, возможно, обычные статьи) будут сортироваться в первую очередь по этому полю. Чем меньше число, тем выше приоритет. Используется для формирования меню, навигации, разделов и т.д.', verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='tbarticle',
            name='j_article_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с дополнительными данными статьи. Может быть понадобится. Например, можно хранить информацию об источнике данных, авторе статьи, ссылках на внешние ресурсы, историю переименований slug и т.д.', null=True, verbose_name='Метаданные статьи'),
        ),
        migrations.AlterField(
            model_name='tbarticle',
            name='k_article_to_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Обложка или иллюстрация статьи из файлового хранилища (django_filer). Для получения метаданных: TbImageMetadata.objects.filter(k_image_to_image=article.k_article_to_image).<br/><b>ВАЖНО</b>: Так как статья привязывается к исполнителям, лейблам, продавцам, музыкальным стилям, её изображение можно использовать как логотип, пиктограмму или баннер этих сущностей. Рекомендуется использовать прозрачный фон (движок поддерживает SVG, WebP и PNG).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_to_article', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение для статьи'),
        ),
        migrations.AlterField(
            model_name='tbarticle',
            name='l_article_type',
            field=models.CharField(blank=True, choices=[('artist', 'Artis: артист, группа или бренд'), ('style', 'Slyle: музыкальный стиль'), ('item', 'Item: Альбом, релиз или товар (кассета, hifi, аксессуар)'), ('label', 'Label: Лейбл, издатель или компания'), ('offer', 'Offer: конкретное предложение от продавца'), ('seller', 'Seller: продавец или магазин'), ('blog', 'Новость или блог'), ('action', 'Спецпредложение, акция, распродажа и т.д.'), ('adv', 'Реклама или баннер'), ('HUB', 'СТАТЬЯ-ХАБ (использует DSL для отображения контента)'), ('txt', 'Текстовый контент (для условий конфиденциальности, правил, соглашений и т.д.)'), ('other', 'Другое')], db_index=True, default='other', max_length=7, verbose_name='Тип статьи'),
        ),
    ]
